<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Java异常详解及自定义异常 - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/1a714e6e69c783866786eb48adbda846/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="Java异常详解及自定义异常">
  <meta property="og:description" content="认识异常，掌握异常处理主要的5个关键字：throw、try、catch、final、throws并掌握自定义异常
目录
1、异常概念与体系结构
1、1异常的概念
1、2异常体系结构
1、3异常的分类
编译时异常：
运行时异常 ：
2、异常处理
2、1防御式编程
2、2异常的抛出
2.3 异常的捕获
2.3.1 异常声明throws
2.3.2 try-catch捕获并处理
2.3.3 finally 3、自定义异常类
1、异常概念与体系结构 1、1异常的概念 在Java中，将程序执行过程中发生的不正常的行为称为异常。
比如写代码经常遇到的：
算数异常 System.out.println(10 / 0);
// 执行结果 Exception in thread &#34;main&#34; java.lang.ArithmeticException: / by zero
数组越界异常 int[] arr = {1, 2, 3};
System.out.println(arr[100]);
// 执行结果 Exception in thread &#34;main&#34; java.lang.ArrayIndexOutOfBoundsException: 100
空指针异常 int[] arr = null;
System.out.println(arr.length);
// 执行结果 Exception in thread &#34;main&#34; java.lang.NullPointerException
从上述过程中可以看到，java中不同类型的异常，都有与其对应的类来进行描述。">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-07-08T13:40:23+08:00">
    <meta property="article:modified_time" content="2024-07-08T13:40:23+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Java异常详解及自定义异常</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>认识异常，掌握异常处理主要的5个关键字：throw、try、catch、final、throws并掌握自定义异常</p> 
<hr> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="1%E3%80%81%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5%E4%B8%8E%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84-toc" style="margin-left:0px;"><a href="#1%E3%80%81%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5%E4%B8%8E%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84" rel="nofollow">1、异常概念与体系结构</a></p> 
<p id="1%E3%80%811%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5-toc" style="margin-left:40px;"><a href="#1%E3%80%811%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5" rel="nofollow">1、1异常的概念</a></p> 
<p id="1%E3%80%812%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84-toc" style="margin-left:40px;"><a href="#1%E3%80%812%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84" rel="nofollow">1、2异常体系结构</a></p> 
<p id="%C2%A01%E3%80%813%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB-toc" style="margin-left:40px;"><a href="#%C2%A01%E3%80%813%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB" rel="nofollow"> 1、3异常的分类</a></p> 
<p id="%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A-toc" style="margin-left:80px;"><a href="#%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A" rel="nofollow">编译时异常：</a></p> 
<p id="%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%20%EF%BC%9A-toc" style="margin-left:80px;"><a href="#%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%20%EF%BC%9A" rel="nofollow">运行时异常 ：</a></p> 
<p id="2%E3%80%81%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86-toc" style="margin-left:0px;"><a href="#2%E3%80%81%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86" rel="nofollow">2、异常处理</a></p> 
<p id="%C2%A02%E3%80%811%E9%98%B2%E5%BE%A1%E5%BC%8F%E7%BC%96%E7%A8%8B-toc" style="margin-left:40px;"><a href="#%C2%A02%E3%80%811%E9%98%B2%E5%BE%A1%E5%BC%8F%E7%BC%96%E7%A8%8B" rel="nofollow"> 2、1防御式编程</a></p> 
<p id="2%E3%80%812%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA-toc" style="margin-left:40px;"><a href="#2%E3%80%812%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA" rel="nofollow">2、2异常的抛出</a></p> 
<p id="2.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7-toc" style="margin-left:40px;"><a href="#2.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7" rel="nofollow">2.3 异常的捕获</a></p> 
<p id="2.3.1%20%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows-toc" style="margin-left:80px;"><a href="#2.3.1%20%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows" rel="nofollow">2.3.1 异常声明throws</a></p> 
<p id="2.3.2%20try-catch%E6%8D%95%E8%8E%B7%E5%B9%B6%E5%A4%84%E7%90%86-toc" style="margin-left:80px;"><a href="#2.3.2%20try-catch%E6%8D%95%E8%8E%B7%E5%B9%B6%E5%A4%84%E7%90%86" rel="nofollow">2.3.2 try-catch捕获并处理</a></p> 
<p id="2.3.3%20finally%C2%A0-toc" style="margin-left:80px;"><a href="#2.3.3%20finally%C2%A0" rel="nofollow">2.3.3 finally </a></p> 
<p id="%C2%A03%E3%80%81%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB-toc" style="margin-left:0px;"><a href="#%C2%A03%E3%80%81%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB" rel="nofollow"> 3、自定义异常类</a></p> 
<hr id="hr-toc"> 
<p></p> 
<h2>1、异常概念与体系结构</h2> 
<h3 id="1%E3%80%811%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5">1、1异常的概念</h3> 
<p>在Java中，将程序执行过程中发生的不正常的行为称为<strong><span style="background-color:#ffd900;">异常</span></strong>。</p> 
<p>比如写代码经常遇到的：</p> 
<ul><li>算数异常</li></ul> 
<blockquote> 
 <p>System.out.println(10 / 0);</p> 
 <p>// 执行结果 Exception in thread "main" java.lang.<span style="color:#fe2c24;">ArithmeticException</span>: / by zero</p> 
</blockquote> 
<ul><li>数组越界异常</li></ul> 
<blockquote> 
 <p>int[] arr = {1, 2, 3};</p> 
 <p>System.out.println(arr[100]);</p> 
 <p>// 执行结果 Exception in thread "main" java.lang<span style="color:#fe2c24;">.ArrayIndexOutOfBoundsException</span>: 100</p> 
</blockquote> 
<ul><li>空指针异常</li></ul> 
<blockquote> 
 <p>int[] arr = null;</p> 
 <p>System.out.println(arr.length);</p> 
 <p>// 执行结果 Exception in thread "main" java.lang<strong><span style="color:#fe2c24;">.NullPointerException</span></strong></p> 
</blockquote> 
<p>从上述过程中可以看到，<strong><span style="background-color:#ffd900;">java中不同类型的异常，都有与其对应的类来进行描述。</span></strong></p> 
<h3 id="1%E3%80%812%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84">1、2异常体系结构</h3> 
<p>异常种类繁多，为了对不同异常或者错误进行很好的分类管理，Java内部维护了一个异常的体系结构：</p> 
<p><img alt="" height="657" src="https://images2.imgbox.com/cc/90/xC48OdjB_o.jpg" width="320"></p> 
<p>从上图中可以看到：</p> 
<blockquote> 
 <ol><li>Throwable：是异常体系的顶层类，其派生出两个重要的子类, Error 和 Exception</li><li> Error：指的是Java虚拟机无法解决的严重问题，比如：JVM的内部错误、资源耗尽等，典型代表： StackOverflowError和OutOfMemoryError，一旦发生回力乏术。</li><li>Exception：异常产生后程序员可以通过代码进行处理，使程序继续执行。比如：感冒、发烧。我们平时所说 的异常就是Exception。 </li></ol> 
</blockquote> 
<h3 id="%C2%A01%E3%80%813%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB"> 1、3异常的分类</h3> 
<h4 id="%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A">编译时异常：</h4> 
<p>在程序编译期间发生的异常，称为编译时异常，也称为受检查异常(Checked Exception）</p> 
<blockquote> 
 <pre>public class Test {
    public static void main(String[] args) {
        Person person=new Person("zhangsan",18);
        Person person2=(Person) person.clone();
        System.out.println(person2);
    }
}</pre> 
 <p>//java: 未报告的异常错误java.lang.CloneNotSupportedException; 必须对其进行捕获或声明以便抛出</p> 
</blockquote> 
<h4 id="%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%20%EF%BC%9A">运行时异常 ：</h4> 
<p><strong><span style="background-color:#ffd900;">在程序执行期间发生的异常，称为运行时异常，也称为非受检查异常(Unchecked Exception)</span></strong></p> 
<p><strong>RunTimeException以及其子类对应的异常，都称为运行时异常。比如：NullPointerException、 ArrayIndexOutOfBoundsException、ArithmeticException。</strong></p> 
<p><span style="color:#fe2c24;"><span style="background-color:#fbd4d0;">注意：编译时出现的语法性错误，不能称之为异常。</span></span>例如将 System.out.println 拼写错了, 写成了 system.out.println. 此时编译过程中就会出错, 这是 "编译期" 出错。而运行时指的是程序已经编译通过得到 class 文件了, 再由 JVM 执行过程中出现的错误 </p> 
<hr> 
<h2 id="2%E3%80%81%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86">2、异常处理</h2> 
<h3 id="%C2%A02%E3%80%811%E9%98%B2%E5%BE%A1%E5%BC%8F%E7%BC%96%E7%A8%8B"> 2、1防御式编程</h3> 
<p><span style="color:#fe2c24;"><strong>1、LBYL:</strong></span> Look Before You Leap. 在操作之前就做充分的检查. 即：事前防御型</p> 
<blockquote> 
 <p>boolean ret = false;</p> 
 <p> ret = 登陆游戏();</p> 
 <p> if (!ret) {<!-- --></p> 
 <p> 处理登陆游戏错误;</p> 
 <p> return;</p> 
 <p>}</p> 
 <p> ret = 开始匹配();</p> 
 <p> if (!ret) {<!-- --></p> 
 <p> 处理匹配错误;</p> 
 <p> return;</p> 
 <p>}</p> 
 <p> ret = 游戏确认();</p> 
 <p> if (!ret) {<!-- --></p> 
 <p> 处理游戏确认错误;</p> 
 <p> return;</p> 
 <p>}</p> 
 <p> ret = 选择英雄();</p> 
 <p> if (!ret) {<!-- --></p> 
 <p> 处理选择英雄错误;</p> 
 <p> return;</p> 
 <p> }</p> 
 <p> ret = 载入游戏画面();</p> 
 <p> if (!ret) {<!-- --></p> 
 <p> 处理载入游戏错误;</p> 
 <p> return;</p> 
 <p> }</p> 
</blockquote> 
<p>缺陷：正常流程和错误处理流程代码混在一起, 代码整体显的比较混乱。</p> 
<p><strong><span style="color:#fe2c24;">2、 EAFP:</span></strong> It's Easier to Ask Forgiveness than Permission. "事后获取原谅比事前获取许可更容易". 也就是先操 作, 遇到问题再处理. 即：事后认错型 </p> 
<p><strong>下面学习EAFP处理异常。</strong></p> 
<p><strong><span style="background-color:#ffd900;">在Java中，异常处理主要的5个关键字：throw、try、catch、final、throws。</span></strong></p> 
<h3 id="2%E3%80%812%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA">2、2异常的抛出</h3> 
<p>在编写程序时，如果程序中出现错误，此时就需要将错误的信息告知给调用者。</p> 
<p> 在Java中，可以借助throw关键字，抛出一个指定的异常对象，将错误信息告知给调用者。</p> 
<blockquote> 
 <pre>if (null == array) {
   <span style="color:#fe2c24;"> throw new NullPointerException("空指针异常");</span>
}
if (index &lt; 0 || index &gt; array.length) {
    <span style="color:#fe2c24;">throw new ArrayIndexBoundsException("数组越界异常");</span>
}</pre> 
</blockquote> 
<p>【注意事项】</p> 
<blockquote> 
 <ol><li> throw必须写在方法体内部</li><li>抛出的对象必须是Exception 或者 Exception 的子类对象</li><li> 如果抛出的是 RunTimeException 或者 RunTimeException 的子类，则可以不用处理，直接交给JVM来处理</li><li> 如果抛出的是编译时异常，用户必须处理，否则无法通过编译</li><li>异常一旦抛出，其后的代码就不会执行 </li></ol> 
</blockquote> 
<h3 id="2.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7">2.3 异常的捕获</h3> 
<p> 异常的捕获，也就是异常的具体处理方式，主要有两种：异常声明throws 以及 try-catch捕获处理。</p> 
<h4 id="2.3.1%20%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows">2.3.1 异常声明throws</h4> 
<p>处在方法声明时参数列表之后，当方法中抛出编译时异常，用户不想处理该异常，此时就可以借助throws将异常抛 给方法的调用者来处理。即当前方法不处理异常，提醒方法的调用者处理异常</p> 
<blockquote> 
 <pre>public int getElement(int[] array, int index) <span style="color:#fe2c24;">throws<span style="color:#ed7976;"> </span>NullPointerException, ArrayIndexBoundsException</span><span style="color:#ed7976;"> </span>{
    if (null == array) {
        throw new NullPointerException("空指针异常");
    }
    if (index &lt; 0 || index &gt; array.length) {
        throw new ArrayIndexBoundsException("数组越界异常");
    }
    return array[index];
}
</pre> 
</blockquote> 
<p>【注意事项】</p> 
<blockquote> 
 <ol><li>throws必须跟在方法的参数列表之后</li><li>声明的异常必须是 Exception 或者 Exception 的子类</li><li>方法内部如果抛出了多个异常，throws之后必须跟多个异常类型，之间用逗号隔开，<span style="background-color:#fbd4d0;">如果抛出多个异常类型 具有父子关系，直接声明父类即可。 </span></li><li>调用 声明抛出异常的方法时，调用者必须对该异常进行处理，或者继续使用throws抛出，如： <pre>public static void main(String[] args) <span style="color:#fe2c24;">throws NullPointerException, ArrayIndexBoundsException </span>{
    int[]array={1,2,3,4,5};
    ArrayException arrayException=new ArrayException();
   arrayException.getElement(array,6);
}</pre> </li></ol> 
</blockquote> 
<h4 id="2.3.2%20try-catch%E6%8D%95%E8%8E%B7%E5%B9%B6%E5%A4%84%E7%90%86">2.3.2 try-catch捕获并处理</h4> 
<p> throws对异常并没有真正处理，要将异常报告给抛出异常方法的调用者，由调用者处理。如果真正要对异常进行 处理，就需要try-catch。</p> 
<p>语法格式：</p> 
<blockquote> 
 <pre> try{
// 将可能出现异常的代码放在这里
        }catch(要捕获的异常类型 e){
// 如果try中的代码抛出异常了，此处catch捕获时异常类型与try中抛出的异常类型一致时，或者是try中抛出异常的基类
            时，就会被捕获到
// 对异常就可以正常处理，处理完成后，跳出try-catch结构，继续执行后序代码
        }[catch(异常类型 e){
// 对异常进行处理
        }finally{
// 此处代码一定会被执行到
        }]
// 后序代码
// 当异常被捕获到时，异常就被处理了，这里的后序代码一定会执行
// 如果捕获了，由于捕获时类型不对，那就没有捕获到，这里的代码就不会被执行
        注意：
        1. []中表示可选项，可以添加，也可以不用添加
        2. try中的代码可能会抛出异常，也可能不会</pre> 
</blockquote> 
<p>【注意事项】</p> 
<ul><li> try块内抛出异常位置之后的代码将不会被执行</li><li> 如果抛出异常类型与catch时异常类型不匹配，即异常不会被成功捕获，也就不会被处理，继续往外抛，直到 JVM收到后中断程序----异常是按照类型来捕获的 </li><li>try中可能会抛出多个不同的异常对象，则必须用多个catch来捕获----即多种异常，多次捕获</li><li>如果多个异常的处理方式是完全相同, 也可以写成这样：</li></ul> 
<blockquote> 
 <p> catch ( ArrayIndexOutOfBoundsException | NullPointerException e ) {<!-- --></p> 
 <p> ...</p> 
 <p>  } </p> 
</blockquote> 
<ul><li>如果异常之间具有父子关系，一定是子类异常在前catch，父类异常在后catch，否则语法错误： </li><li> 可以通过一个catch捕获所有的异常，即多个异常，一次捕获(不推荐) </li></ul> 
<h4 id="2.3.3%20finally%C2%A0">2.3.3 finally </h4> 
<p>在写程序时，有些特定的代码，不论程序是否发生异常，都需要执行，比如程序中打开的资源：网络连接、数据库 连接、IO流等，<strong><span style="background-color:#ffd900;">在程序正常或者异常退出时，必须要对资源进进行回收。另外，因为异常会引发程序的跳转，可能 导致有些语句执行不到，finally就是用来解决这个问题的。</span></strong></p> 
<blockquote> 
 <pre>public static void main(String[] args) {
    try{
        int[] arr = {1,2,3};
        arr[100] = 10;
        arr[0] = 10;
    }catch (ArrayIndexOutOfBoundsException e){
        System.out.println(e);
    }finally {
        System.out.println("finally中的代码一定会执行");
    }
    System.out.println("如果没有抛出异常，或者异常被处理了，try-catch后的代码也会执行");
}</pre> 
</blockquote> 
<p> 如果正常输入，成功接收输入后程序就返回了，try-catch-finally之后的代码根本就没有执行，即输入流 就没有被释放，造成资源泄漏。所以，一般在finally中进行一些资源清理的扫尾工作，因为finally中的代码一定会执行的，</p> 
<hr> 
<p>【异常处理流程总结】</p> 
<ul><li>程序先执行 try 中的代码</li><li>如果 try 中的代码出现异常, 就会结束 try 中的代码, 看和 catch 中的异常类型是否匹配.</li><li>如果找到匹配的异常类型, 就会执行 catch 中的代码</li><li>如果没有找到匹配的异常类型, 就会将异常向上传递到上层调用者.</li><li>无论是否找到匹配的异常类型, finally 中的代码都会被执行到(在该方法结束之前执行).</li><li>如果上层调用者也没有处理的了异常, 就继续向上传递.</li><li>一直到 main 方法也没有合适的代码处理异常, 就会交给 JVM 来进行处理, 此时程序就会异常终止.</li></ul> 
<h2 id="%C2%A03%E3%80%81%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB"> 3、自定义异常类</h2> 
<p>Java 中虽然已经内置了丰富的异常类, 但是并不能完全表示实际开发中所遇到的一些异常，此时就需要维护符合我 们实际情况的异常结构.</p> 
<p>例如, 我们实现一个用户登陆功能.</p> 
<ul><li><span style="background-color:#ffd900;">定义异常类</span></li></ul> 
<p>步骤：</p> 
<p>1、 自定义异常类，然后继承自Exception 或者 RunTimeException</p> 
<p>2、 实现一个带有String类型参数的构造方法，参数含义：出现异常的原因</p> 
<blockquote> 
 <p></p> 
 <pre>public class PassWordException extends Exception{
    public PassWordException() {
        super();
    }

    public PassWordException(String message) {
        super(message);
    }
}</pre> 
 <pre>public class UseNameException extends Exception{
    public UseNameException() {
        super();
    }
    public UseNameException(String message) {
        super(message);
    }
}</pre> 
</blockquote> 
<ul><li><span style="background-color:#ffd900;">2、定义登录类</span></li></ul> 
<p>步骤：</p> 
<p>1、提供成员变量与构造方法</p> 
<p>2、提供抛出异常的方法</p> 
<blockquote> 
 <pre>class Login{
    private String useName;
    private String passWord;

    public Login(String useName, String passWord) {
        this.useName = useName;
        this.passWord = passWord;
    }

    public String getUseName() {
        return useName;
    }

    public void setUseName(String useName) {
        this.useName = useName;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public void logInfo(String useName,String passWord) throws UseNameException,PassWordException {
        if(!this.useName.equals(useName)){
            throw new UseNameException("用户名错误");
        }
        if(!this.passWord.equals(passWord)){
            throw new PassWordException("密码错误");
        }
        System.out.println("登陆成功");
    }
}</pre> 
</blockquote> 
<ul><li><span style="background-color:#ffd900;">3、定义测试类，捕获异常 </span></li></ul> 
<blockquote> 
 <pre>public class Test {

    public static void main(String[] args) {
        Login login= new Login("27589","26163");

        try{
            login.logInfo("27589","2616");
        } catch (PassWordException e) {
            e.printStackTrace();
        } catch (UseNameException e) {
            e.printStackTrace();
        }
    }
}</pre> 
 <p> </p> 
 <p>  //com.exception.PassWordException: 密码错误<br>   // at com.exception.Login.logInfo(Test.java:32) </p> 
 <p>  //at com.exception.Test.main(Test.java:43)</p> 
</blockquote>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/8e76bc7dfd22eb9365f6c128405fce86/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Python前沿技术：机器学习与人工智能</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/32c94a33063a3972b54fe7347dcbf8cc/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">【EI稳定检索】第五届大数据、人工智能与软件工程国际研讨会（ICBASE 2024）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>