<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>认识JAVA中的异常 - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/72418d0909956de6c9e5321222f56b5c/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="认识JAVA中的异常">
  <meta property="og:description" content="目录： 一. 异常概念与体系结构 二. 异常的处理 三. 自定义异常类 一. 异常概念与体系结构: 1 异常的概念:在 Java 中，将程序执行过程中发生的 不正常行为 称为异常， 如：算数异常： ArithmeticException System.out.println(10 / 0); // 执行结果 Exception in thread &#34;main&#34; java.lang.ArithmeticException: / by zero 数组越界异常：ArrayIndexOutOfBoundsException
int[] arr = {1, 2, 3}; System.out.println(arr[100]); // 执行结果 Exception in thread &#34;main&#34; java.lang.ArrayIndexOutOfBoundsException: 100 空指针异常： NullPointerException int[] arr = null; System.out.println(arr.length); // 执行结果 Exception in thread &#34;main&#34; java.lang.NullPointerException 2.异常的体系结构：异常种类繁多，为了对不同异常或者错误进行很好的分类管理， Java 内部维护了一个 异常的体系结构 如图： 从图中可以看出： (1).Throwable ： 是异常体系的顶层类，其派生出两个重要的子类, Error 和 Exception (2).">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-06-01T21:28:43+08:00">
    <meta property="article:modified_time" content="2024-06-01T21:28:43+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">认识JAVA中的异常</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <div> 
 <span style="color:#511b78;"><strong>目录：</strong></span> 
</div> 
<div> 
 <strong><span style="color:#fe2c24;">一. 异常概念与体系结构 </span></strong> 
</div> 
<div> 
 <strong><span style="color:#fe2c24;">二.</span></strong> 
 <span style="color:#fe2c24;"><strong>异常的处理</strong></span> 
</div> 
<div> 
 <div> 
  <span style="color:#fe2c24;"><strong>三. 自定义异常类</strong></span> 
 </div> 
</div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div></div> 
<div> 
 <strong><span style="color:#fe2c24;">一. 异常概念与体系结构:</span></strong> 
</div> 
<div></div> 
<div> 
 <div> 
  <span style="color:#333333;"><strong>1 异常的概念:在</strong></span> 
  <span style="color:#333333;"><strong>Java</strong></span> 
  <span style="color:#333333;"><strong>中，将程序执行过程中发生的</strong></span> 
  <span style="color:#956fe7;"><strong>不正常行为</strong></span> 
  <span style="color:#333333;"><strong>称为异常，</strong></span> 
 </div> 
 <div> 
  <strong>如：算数异常</strong>： 
  <span style="color:#fe2c24;"><strong>ArithmeticException</strong></span> 
 </div> 
 <div></div> 
 <div> 
  <pre><code class="language-java">System.out.println(10 / 0);
// 执行结果
Exception in thread "main" java.lang.ArithmeticException: / by zero</code></pre> 
  <p></p> 
  <p><strong>数组越界异常：<span style="color:#fe2c24;">ArrayIndexOutOfBoundsException</span></strong></p> 
  <pre><code class="language-java">int[] arr = {1, 2, 3};
System.out.println(arr[100]);
// 执行结果
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 100</code></pre> 
  <div></div> 
  <div> 
   <span style="color:#333333;"><strong>空指针异常：</strong></span> 
   <span style="color:#fe2c24;"><strong>NullPointerException</strong></span> 
  </div> 
  <div></div> 
  <div> 
   <pre><code class="language-java">int[] arr = null;
System.out.println(arr.length);
// 执行结果
Exception in thread "main" java.lang.NullPointerException</code></pre> 
   <p></p> 
   <p></p> 
   <div> 
    <span style="color:#333333;"><strong>2.异常的体系结构：异常种类繁多，为了对不同异常或者错误进行很好的分类管理，</strong></span> 
    <strong><span style="color:#333333;">Java</span></strong> 
    <span style="color:#333333;"><strong>内部维护了一个</strong></span> 
    <span style="color:#956fe7;"><strong>异常的体系结构</strong></span> 
    <span style="color:#333333;"><strong>如图：</strong></span> 
   </div> 
   <div> 
    <img alt="" height="708" src="https://images2.imgbox.com/fd/d7/rStrRHHE_o.png" width="404"> 
   </div> 
   <div></div> 
   <div></div> 
   <div> 
    <div> 
     <span style="color:#333333;"><strong>从图中可以看出：</strong></span> 
    </div> 
    <div> 
     <span style="color:#333333;"><strong>(1).Throwable</strong></span> 
     <span style="color:#333333;"><strong>：</strong></span> 
     <strong><span style="color:#333333;">是异常体系的顶层类，其派生出两个重要的子类</span><span style="color:#333333;">,</span><span style="color:#956fe7;"> Error</span></strong> 
     <strong><span style="color:#333333;"> </span></strong> 
     <span style="color:#333333;"><strong>和</strong> </span> 
     <span style="color:#956fe7;"><strong>Exception</strong></span> 
    </div> 
    <div></div> 
    <div> 
     <div> 
      <strong><span style="color:#333333;">(2). </span><span style="color:#333333;">Error</span><span style="color:#333333;">：</span><span style="color:#333333;">指的是</span><span style="color:#333333;">Java</span><span style="color:#333333;">虚拟机无法解决的严重问题，比如：</span><span style="color:#956fe7;">JVM的内部错误、资源耗尽等</span><span style="color:#333333;">，典型代表： </span><span style="color:#333333;">StackOverflowError</span><span style="color:#333333;">和</span><span style="color:#333333;">OutOfMemoryError，一旦发生回力乏术。</span></strong> 
     </div> 
     <div></div> 
     <div> 
      <div> 
       <span style="color:#333333;"><strong>(3).Exception</strong></span> 
       <span style="color:#333333;"><strong>：</strong></span> 
       <span style="color:#fe2c24;"><strong>异常产生后程序员可以通过代码进行处理，使程序继续执行。比如：感冒、发烧。我们平时所说的异常就是Exception。</strong></span> 
      </div> 
     </div> 
     <div></div> 
     <div> 
      <span style="color:#511b78;"><strong>OutOfMemoryError为内存泄漏</strong></span> 
      <strong><span style="color:#fe2c24;">：程序中存在未释放的内存资源，导致内存占用不断增加，最终导致内存不足等等</span></strong> 
     </div> 
     <div></div> 
     <div> 
      <strong><span style="color:#333333;">StackOverflowError为：</span><span style="color:#511b78;">无限递归下去导致</span></strong>， 
      <span style="color:#fe2c24;"><strong>超出栈的容量等等</strong></span> 
     </div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div>
       3. 
      <span style="color:#333333;"><strong>异常的分类:分为</strong></span> 
      <span style="color:#333333;"><strong>编译时异常, </strong></span> 
      <span style="color:#333333;"><strong>运行时异常。</strong></span> 
     </div> 
     <div></div> 
     <div> 
      <span style="color:#333333;">(1). <strong>编译时异常:</strong></span> 
      <span style="color:#0d0016;"> <strong>在程序</strong></span> 
      <span style="color:#511b78;"><strong>编译期间</strong></span> 
      <span style="color:#0d0016;"><strong>发生的异常，称为</strong></span> 
      <span style="color:#956fe7;"><strong>编译时异常</strong></span> 
      <span style="color:#0d0016;"><strong>，也称为</strong></span> 
      <span style="color:#956fe7;"><strong>受检查异常</strong></span> 
     </div> 
     <div></div> 
     <div> 
      <strong>如图：这个重写，克隆方法的拷贝，<span style="color:#fe2c24;">没有</span>对其<span style="color:#956fe7;">捕获或声明</span></strong> 
     </div> 
     <div> 
      <img alt="" height="415" src="https://images2.imgbox.com/21/07/c4mti6Wv_o.png" width="1094"> 
     </div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div> 
      <strong>下图则是声明：</strong> 
      <span style="color:#fe2c24;"><strong>就编译通过</strong></span> 
     </div> 
     <div> 
      <img alt="" height="325" src="https://images2.imgbox.com/a0/ca/CtFbUsBu_o.png" width="888"> 
     </div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div></div> 
     <div> 
      <div> 
       <span style="color:#333333;">2. </span> 
       <span style="color:#333333;"><strong>运行时异常：</strong></span> 
      </div> 
      <div> 
       <span style="color:#333333;"><strong>（1）</strong></span> 
       <span style="color:#0d0016;"><strong>在程序</strong></span> 
       <span style="color:#956fe7;"><strong>执行期间</strong></span> 
       <span style="color:#0d0016;"><strong>发生的异常，称为运行时异常，也称为</strong></span> 
       <span style="color:#fe2c24;"><strong>非受检查异常</strong></span> 
      </div> 
      <div> 
       <p><span style="color:#0d0016;"><strong>（2）</strong></span><span style="color:#333333;"><strong>RunTimeException</strong></span><span style="color:#333333;"><strong>以及其子类对应的异常，都称为运行时异常</strong></span><span style="color:#333333;">。</span></p> 
       <p><strong><span style="color:#333333;">比如</span><span style="color:#333333;">NullPointerException</span><span style="color:#333333;">、ArrayIndexOutOfBoundsException、</span><span style="color:#333333;">ArithmeticException</span><span style="color:#333333;">。 </span></strong></p> 
       <div> 
        <strong><span style="color:#fe2c24;">注意：编译时出现的</span><span style="color:#1a439c;">语法性错误</span><span style="color:#fe2c24;">，不能称之为异常。例如将 System.out.println 拼写错了, 写成了</span></strong> 
       </div> 
      </div> 
      <div></div> 
      <div> 
       <strong>这里也用克隆举例子，这里<span style="color:#956fe7;">没有实现克隆接口</span>，却<span style="color:#fe2c24;">编译通过了！！！</span></strong> 
      </div> 
      <div> 
       <img alt="" height="739" src="https://images2.imgbox.com/cd/46/5LWkWzFH_o.png" width="1200"> 
      </div> 
      <div></div> 
      <div></div> 
      <div> 
       <strong>但是运行会有异常：这就是<span style="color:#fe2c24;">非受查异常</span></strong> 
      </div> 
      <div></div> 
      <div> 
       <img alt="" height="298" src="https://images2.imgbox.com/dd/93/d56m3NQq_o.png" width="1200"> 
      </div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div></div> 
      <div> 
       <strong><span style="color:#fe2c24;">二.</span></strong> 
       <span style="color:#fe2c24;"><strong>异常的处理：</strong></span> 
      </div> 
      <div></div> 
      <div></div> 
      <div> 
       <span style="color:#333333;">在Java中，</span> 
       <span style="color:#333333;"><strong>异常处理主要的</strong></span> 
       <span style="color:#333333;"><strong>5</strong></span> 
       <span style="color:#333333;"><strong>个关键字：</strong></span> 
       <span style="color:#333333;"><strong>throw</strong></span> 
       <span style="color:#333333;"><strong>、</strong></span> 
       <span style="color:#333333;"><strong>try</strong></span> 
       <span style="color:#333333;"><strong>、</strong></span> 
       <span style="color:#333333;"><strong>catch</strong></span> 
       <span style="color:#333333;"><strong>、</strong></span> 
       <span style="color:#333333;"><strong>final</strong></span> 
       <span style="color:#333333;"><strong>、</strong></span> 
       <span style="color:#333333;"><strong>throws</strong></span> 
       <span style="color:#333333;">。用好他们就，可以很好的处理异常了。</span> 
      </div> 
      <div> 
       <div></div> 
       <div>
         1. 
        <span style="color:#333333;"><strong>异常的抛出 </strong></span> 
        <strong><span style="color:#0d0016;">：在Java中，可以借助</span><span style="color:#956fe7;">throw关键字</span><span style="color:#0d0016;">，抛出一个指定的异常对象，将</span><span style="color:#494949;">错误信息告知给调用者</span></strong> 
       </div> 
       <div></div> 
       <div>
         注意： 
        <div> 
         <strong><span style="color:#333333;">（1）. throw</span><span style="color:#333333;">必须写在方法体内部 </span></strong> 
        </div> 
        <div> 
         <strong><span style="color:#333333;">（2）. </span><span style="color:#333333;">抛出的对象必须是</span><span style="color:#333333;">Exception </span><span style="color:#333333;">或者</span><span style="color:#333333;"> Exception </span><span style="color:#333333;">的子类对象 </span></strong> 
        </div> 
        <div> 
         <strong><span style="color:#333333;">（3）. </span><span style="color:#956fe7;">如果抛出的是 RunTimeException </span><span style="color:#333333;">或者</span><span style="color:#333333;"> </span><span style="color:#956fe7;">RunTimeException 的子类</span><span style="color:#333333;">，则可以不用处理，</span><span style="color:#fe2c24;">直接交给JVM来处理 </span></strong> 
        </div> 
        <div> 
         <strong><span style="color:#333333;">（4）. </span><span style="color:#333333;">如果抛出的是编译时异常，用户必须处理，否则无法通过编译 </span></strong> 
        </div> 
        <div> 
         <span style="color:#fe2c24;"><strong>（5）. 异常一旦抛出，</strong></span> 
         <span style="color:#511b78;"><strong>其后</strong></span> 
         <span style="color:#fe2c24;"><strong>的代码就不会执行。</strong></span> 
        </div> 
       </div> 
       <div></div> 
      </div> 
      <div>
        如图：这里还用了，try处理catch捕捉 
      </div> 
      <div> 
       <pre><code class="language-java">public static void main(String[] args)throws ArrayIndexOutOfBoundsException {
        int[] array = new int[2];

        //捕捉异常
        try {
            //放可能发生的异常
            System.out.println(array[3]);
            System.out.println("这里不会再执行了");

        }catch (ArrayIndexOutOfBoundsException e) {
            //捕捉异常
            System.out.println("处理了ArrayIndexOutOfBoundsException异常");
            //捕捉，打印异常
            e.printStackTrace();

        }
    }</code></pre> 
       <p></p> 
       <div> 
        <span style="color:#333333;"><strong>2.异常的捕获：异常的捕获，也就是异常的具体处理方式，主要有两种：</strong></span> 
        <span style="color:#956fe7;"><strong>异常声明throws 以及 try-catch捕获处理。</strong></span> 
       </div> 
       <div></div> 
       <div> 
        <img alt="" height="481" src="https://images2.imgbox.com/75/7c/i62PvWyz_o.png" width="1185"> 
       </div> 
       <div> 
        <span style="color:#fe2c24;"><strong>抛出异常：</strong></span> 
       </div> 
       <div> 
        <pre><code class="language-java">public static void OpenConfig(String filename) throws FileNotFoundException {

        if (filename.equals("config.ini")) {
            throw new FileNotFoundException("配置文件名字不对");
        }
    }</code></pre> 
        <p></p> 
       </div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div> 
        <span style="color:#333333;"><strong>3.try-catch</strong></span> 
        <strong><span style="color:#333333;">捕获并处理 </span>：<span style="color:#333333;">throws对异常</span><span style="color:#fe2c24;">并没有真正处理</span><span style="color:#333333;">，而是将异常报告给抛出异常方法的调用者，由调用者处理。如果</span><span style="color:#fe2c24;">真正要对异常进行处理，就需要try-catch。）</span></strong> 
       </div> 
       <div></div> 
       <div></div> 
       <div> 
        <span style="color:#956fe7;"><strong>此时声明一下，然后捕获：（</strong></span> 
        <span style="color:#0d0016;"><strong>直接声明不捕获也可以</strong></span> 
        <span style="color:#956fe7;"><strong>）</strong></span> 
       </div> 
       <div> 
        <pre><code class="language-java">class Exception {
    File file;

    /*
    FileNotFoundException : 编译时异常，表明文件不存在
    此处不处理，也没有能力处理，应该将错误信息报告给调用者，让调用者检查文件名字是否给错误了
    */
    public static void OpenConfig(String filename) throws FileNotFoundException {

        if (filename.equals("config.ini")) {
            throw new FileNotFoundException("配置文件名字不对");
        }
    }

    //捕获
    public static void main(String[] args) {
        try {
            //将可能出现异常的代码放在这里
            OpenConfig("test");
        } catch (FileNotFoundException e) {
            // 如果try中的代码抛出异常了，此处catch捕获时异常类型与try中抛出的异常类型一致时，或者是try中抛出异常的基就会时，就会被捕获到
            e.printStackTrace();
        }finally {
            // 此处代码一定会被执行到,一般用来关闭文件，释放资源
        }

    }
}</code></pre> 
        <div> 
         <span style="color:#fe2c24;"><strong>注意：1.try块内抛出异常位置之后的代码将不会被执行。</strong></span> 
         <div> 
          <span style="color:#fe2c24;"><strong>2. 如果</strong></span> 
          <span style="color:#0d0016;"><strong>抛出异常类型与catch时异常类型不匹配</strong></span> 
          <span style="color:#fe2c24;"><strong>，即异常不会被成功捕获，也就不会被处理，继续往外抛</strong></span> 
          <span style="color:#0d0016;"><strong>，直到 JVM收到后中断程序。</strong></span> 
          <span style="color:#fe2c24;"><strong>（一般写法是，用父类异常在最后面兜底）</strong></span> 
         </div> 
        </div> 
        <p></p> 
        <div> 
         <span style="color:#333333;"><strong>4.finally：</strong></span> 
         <div> 
          <span style="color:#333333;">在写程序时，</span> 
          <span style="color:#fe2c24;"><strong>有些特定的代码，不论程序是否发生异常，都需要执行，比如程序中打开的资源</strong></span> 
          <span style="color:#333333;">：网络连接、数据库连接、IO</span> 
          <span style="color:#333333;">流等，</span> 
          <span style="color:#fe2c24;"><strong>在程序正常或者异常退出时，必须要对资源进进行回收</strong></span> 
          <span style="color:#333333;">。另外，因为</span> 
          <span style="color:#fe2c24;"><strong>异常会引发程序的跳转，可能导致有些语句执行不到</strong></span> 
          <span style="color:#333333;">，</span> 
          <strong><span style="color:#333333;">finally</span></strong> 
          <span style="color:#333333;">就是用来解决这个问题的。</span> 
         </div> 
         <div></div> 
         <div> 
          <span style="color:#9c8ec1;"><strong>还有</strong></span> 
          <span style="color:#333333;"><strong>finally</strong></span> 
          <span style="color:#333333;"><strong>中的代码一定会执行的，一般在</strong></span> 
          <span style="color:#333333;"><strong>finally</strong></span> 
          <span style="color:#333333;"><strong>中进行一些资源清理的扫尾工作</strong></span> 
         </div> 
        </div> 
        <div></div> 
       </div> 
       <div></div> 
       <div></div> 
       <div></div> 
       <div> 
        <pre><code class="language-java">语法格式：
try{
// 可能会发生异常的代码
}catch(异常类型 e){
// 对捕获到的异常进行处理
}finally{
// 此处的语句无论是否发生异常，都会被执行到
}
// 如果没有抛出异常，或者异常被捕获处理了，这里的代码也会执行</code></pre> 
        <p></p> 
        <p></p> 
        <div> 
         <span style="color:#333333;"><strong>（补充）异常的处理流程：</strong></span> 
         <span style="color:#fe2c24;"><strong>如果本方法中没有合适的处理异常的方式, 就会沿着调用栈向上传递</strong></span> 
         <span style="color:#956fe7;"><strong>（</strong></span> 
         <span style="color:#1c7331;"><strong>方法1--》方法2--》方法3---》main方法----》jvm）</strong></span> 
        </div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div></div> 
        <div> 
         <span style="color:#fe2c24;"><strong>三. 自定义异常类：</strong></span> 
        </div> 
        <div></div> 
        <div> 
         <div> 
          <strong><span style="color:#333333;">Java </span><span style="color:#333333;">中虽然已经内置了丰富的异常类</span><span style="color:#333333;">, </span><span style="color:#956fe7;">但是并不能完全表示实际开发中所遇到的一些异常</span><span style="color:#333333;">，此时就需要</span><span style="color:#956fe7;">维护符合我们实际情况</span><span style="color:#333333;">的异常结构.</span><span style="color:#fe2c24;">就需要自定义异常</span></strong> 
         </div> 
         <div></div> 
         <div> 
          <div> 
           <strong><span style="color:#333333;">例如</span><span style="color:#333333;">, </span><span style="color:#333333;">我们实现一个用户登陆功能：</span></strong> 
          </div> 
          <div> 
           <span style="color:#956fe7;"><strong>根据业务此时我们在处理用户名密码错误的时候可能就需要抛出两种异常</strong></span> 
          </div> 
          <div></div> 
          <div></div> 
          <div> 
           <span style="color:#fe2c24;"><strong>注意：</strong></span> 
           <div> 
            <span style="color:#fe2c24;"><strong>1.自定义异常类，然后继承自Exception 或者 RunTimeException </strong></span> 
           </div> 
           <div> 
            <span style="color:#fe2c24;"><strong>2. 实现一个带有String类型参数的构造方法，参数含义：出现异常的原因</strong></span> 
           </div> 
          </div> 
          <div> 
           <img alt="" height="125" src="https://images2.imgbox.com/1c/d8/IjkE0PG2_o.png" width="889"> 
          </div> 
         </div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div> 
          <img alt="" height="325" src="https://images2.imgbox.com/da/bc/xfEqxhCf_o.png" width="791"> 
         </div> 
         <div></div> 
         <div> 
          <img alt="" height="263" src="https://images2.imgbox.com/50/9b/S9IOlAWW_o.png" width="908"> 
         </div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div></div> 
         <div>
           业务代码： 
         </div> 
         <div></div> 
         <div> 
          <pre><code class="language-java">class login {
    private String userName;
    private String passWord;


    public  void loginFo(String userName, String passWord)throws UserException,PassWardException{
        if (!this.userName.equals(userName)) {
            throw new UserException("抛出自定义，的用户名错误异常");

        }

        if (!this.passWord.equals(passWord)) {
            
            throw new PassWardException("抛出密码自定义，的用密码错误异常");

        }

        System.out.println("登录成功！");
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
}



public class TestException {
    public static void main(String[] args) throws UserException {
        login login = new login();
        login.setPassWord("321");
        login.setUserName("haha");
        login.loginFo("haha", "323");

        /*try {
            login.loginFo("haha", "323");

        }catch (UserException e) {
            e.printStackTrace();
        }catch (PassWardException e) {
            e.printStackTrace();
        }finally {

        }*/
    }
}</code></pre> 
          <p>                       <img alt="" height="720" src="https://images2.imgbox.com/59/9c/DjGiNsOW_o.png" width="720"></p> 
         </div> 
        </div> 
       </div> 
      </div> 
     </div> 
    </div> 
   </div> 
  </div> 
 </div> 
</div>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/b22453e28de92455b2703bd4d4152ab5/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">【数据结构】——堆</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/0fd4a8277a67f1c1318b1787ef3c58ba/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">【Java】面向对象的三大特征：封装、继承、多态</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>